Update docker and workflow for testing

diff --git a/.github/workflows/build-docker.yml b/.github/workflows/build-docker.yml
--- a/.github/workflows/build-docker.yml
+++ b/.github/workflows/build-docker.yml
@@ -122,13 +122,13 @@ jobs:
     -
       name: Test Image
       run: |
-        output=$(docker run --rm ${{ env.TEST_TAG}} /bin/sh -c "deno --version | grep -q ${{ matrix.deno-version }} && echo 'OK' || echo 'KO'")
-        # if [ "$output" == "OK" ]; then
-        #   echo "Test Passed"
-        # else
-        #   echo "Test Failed"
-        #   exit 1
-        # fi
+        output=$(docker run --rm ${{ env.TEST_TAG}} /bin/sh -c "LD_LIBRARY_PATH=/usr/local/lib:/lib:/lib64 deno --version | grep -q ${{ matrix.deno-version }} && echo 'OK' || echo 'KO'")
+        if [ "$output" == "OK" ]; then
+          echo "Test Passed"
+        else
+          echo "Test Failed"
+          exit 1
+        fi
     
     -
       name: Login to DockerHub
