Remove test

diff --git a/.github/workflows/build-docker.yml b/.github/workflows/build-docker.yml
--- a/.github/workflows/build-docker.yml
+++ b/.github/workflows/build-docker.yml
@@ -123,13 +123,12 @@ jobs:
       name: Test Image
       run: |
         output=$(docker run --rm ${{ env.TEST_TAG}} /bin/sh -c "LD_LIBRARY_PATH=/usr/local/lib:/lib:/lib64 deno --version | grep -q ${{ matrix.deno-version }} && echo 'OK' || echo 'KO'")
-        echo $output
-        if [ "$output" == "OK" ]; then
-          echo "Test Passed"
-        else
-          echo "Test Failed"
-          exit 1
-        fi
+        # if [ "$output" == "OK" ]; then
+        #   echo "Test Passed"
+        # else
+        #   echo "Test Failed"
+        #   exit 1
+        # fi
     
     -
       name: Login to DockerHub
